name: Cron Job

on:
  schedule:
    # Runs every hour (at minute 0)
    - cron: '0,30 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Echo message
        shell: bash
        run: echo "🚫👑 no kings"
