name: Cron Job

on:
  schedule:
    # Runs every hour (at minute 0)
    - cron: '0 * * * *'

jobs:
  run:
    runs-on: ubuntu-slim

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1

      - name: Echo message
        shell: bash
        run: echo "🚫👑 no kings"
